Username Validation
akhilchoudhary2k/MindMatch-kgp pull request #27
Opened 2022-10-21 09:23 UTC by ritiksp2411

2022-10-21 09:33 UTC, ritiksp2411 commented
@akhilchoudhary2k Please review it once

2022-10-21 10:39 UTC, akhilchoudhary2k requested changes

2022-10-21 10:39 UTC, akhilchoudhary2k commented on app.js
> +            var trimmedUsername = req.body.username.trim();
Keep the `trim()` intact.
Additionally put a check for cases when there is spaces in between, i.e. username is of >1 words

For example: `abc def` this username should not be allowed
We must throw error to fill the form again.

2022-10-21 10:39 UTC, akhilchoudhary2k commented on app.js
> +            if(trimmedUsername.length > 4) {
Make it >=

2022-10-21 10:39 UTC, akhilchoudhary2k commented on app.js
> +                var message = "username should be more than 4 characters";
username should be ~~more than~~ atleast 4 characters.

2022-10-22 09:08 UTC, ritiksp2411 commented
@akhilchoudhary2k review it once

2022-10-22 09:11 UTC, akhilchoudhary2k requested changes

2022-10-22 09:11 UTC, akhilchoudhary2k commented on app.js
> -    if(schema.validate(req.body.password2)){
Why are you removing password validation ??

2022-10-22 09:11 UTC, akhilchoudhary2k commented
@ritiksp2411 Seems like you didn't fetch the latest code before raising the PR.

2022-10-22 09:32 UTC, closed without merging