fixed the bug on entering wrong credentials
akhilchoudhary2k/MindMatch-kgp pull request #41
Opened 2022-10-28 11:51 UTC by rehanmm

2022-10-28 18:16 UTC, akhilchoudhary2k requested changes

2022-10-28 18:16 UTC, akhilchoudhary2k commented on app.js
> +    var running_locally = true;
Change it back to false, because it's just for local testing.

2022-10-28 18:16 UTC, akhilchoudhary2k commented on app.js
> +
correct the indentation and remove un-necessary whitespaces like these empty lines.

2022-10-28 18:16 UTC, akhilchoudhary2k commented on app.js
> +                                                        else res.redirect("/UserHome");
fix the indentation pls

2022-10-28 18:16 UTC, akhilchoudhary2k commented on app.js
> +                    res.render("login", {
here if req.body.username === admin then render the `adminlogin` page
otherwise `login` page

2022-10-28 18:17 UTC, akhilchoudhary2k commented
@rehanmm just do these minimal changes I suggested, other than this everything looks good.
Great work !!

2022-10-29 07:55 UTC, akhilchoudhary2k commented
@rehanmm you have created so much unnecessary diff in app.js file (have a look)
and it's very difficult for me to go through the changes now.
I think you changed indentation in the whole file, instead you should have done it only with the part of code you added.

2022-10-29 07:57 UTC, akhilchoudhary2k commented on app.js
> +
@rehanmm Here I meant: give one tab indentation in front of app.post(...) so that indentation scheme matches with the rest of code.

2022-10-29 08:15 UTC, akhilchoudhary2k commented
@rehanmm EDIT: I reviewed your changes with **ignore whitespace**, so it looks good.
Anyways the whole file indentation changed one and the same thing.

2022-10-29 08:18 UTC, akhilchoudhary2k approved these changes

2022-10-29 08:20 UTC, merged

2022-10-29 08:36 UTC, akhilchoudhary2k commented
@rehanmm Thanks for showing interest and getting your PR merged !!

There are 2 easy open issues would you like to work? since there's little or no progress by current assignees
Have a look: https://github.com/akhilchoudhary2k/MindMatch-kgp/issues/35 & https://github.com/akhilchoudhary2k/MindMatch-kgp/issues/38

2022-10-29 08:53 UTC, rehanmm commented
> @rehanmm you have created so much unnecessary diff in app.js file (have a look) and it's very difficult for me to go through the changes now. I think you changed indentation in the whole file, instead you should have done it only with the part of code you added.

@akhilchoudhary2k  it happened because i applied shortcut for format document and  it formatted the whole document instead of selected lines .i noticed it after  request to merge